language: node_js
node_js:
  - "10"
env:
  - NODE_ENV=test

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - mkdir $TRAVIS_BUILD_DIR/config
  - mkdir $TRAVIS_BUILD_DIR/config/ssl
  - openssl req -new -x509 -newkey rsa:4096 -keyout ./config/ssl/musicserver.key -out ./config/ssl/musicserver.crt -days 365 -subj "/C=DE/ST=Bavaria/L=Test/O=Teste/OU=DE/CN=www.example.com" -nodes
  - npm install
  - npm run compile
  - docker-compose up -d
  - sudo chmod -R 777 data

script:
  - npm test
