language: node_js
env:
  - NODE_ENV=test

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - mkdir $TRAVIS_BUILD_DIR/config/ssl
  - openssl req -new -x509 -newkey rsa:4096 -keyout ./config/ssl/musicserver.key -out ./config/ssl/musicserver.crt -days 365 -subj "/C=DE/ST=Bavaria/L=Test/O=Teste/OU=DE/CN=www.example.com" -nodes
  - docker-compse up

script:
  - npm test
